language: objective-c
osx_image: xcode10.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - COMMAND="test-iOS"
  - COMMAND="examples"
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- swift -version
- swiftlint --strict
- sh build.sh "$COMMAND"
