version: 2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint --strict

  test-iOS:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            sh build.sh test-iOS

  examples:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: examples
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            sh build.sh examples

workflows:
  version: 2
  swiftlint:
      - swiftlint
  build-and-test:
    requires:
      - swiftlint
    jobs:
      - test-iOS
      - examples
