version: 2

common: &common
  macos:
    xcode: "11.0.0"

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  <<: *common
  swiftlint:
    steps:
      - checkout
      - run:
          name: Install swiftlint(0.35.0)
          command: |
            brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ab64b13d26a3f8617689e3bc7e73a209d11f1bc8/Formula/swiftlint.rb
      - run: swiftlint version && swiftlint --strict

  test-iOS:
    <<: *common
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            IOS_SDK="iphonesimulator13.0" \
                IOS_DESTINATION_PHONE="OS=13.0,name=iPhone 11" \
                sh build.sh test-iOS

  test-iOS12:
    macos:
      xcode:
        "10.2.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            IOS_SDK="iphonesimulator12.2" \
                IOS_DESTINATION_PHONE="OS=12.2,name=iPhone Xs" \
                sh build.sh test-iOS


  examples:
    <<: *common
    steps:
      - checkout
      - run:
          name: examples
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cfk
            IOS_SDK="iphonesimulator13.0" \
                IOS_DESTINATION_PHONE="OS=13.0,name=iPhone 11" \
                sh build.sh examples

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - test-iOS:
          requires:
            - swiftlint
      - test-iOS12:
          requires:
            - swiftlint
      - examples:
          requires:
            - swiftlint
